apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: Xyz_$!8
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      volumes:
      - name: example-configmap-volume
        configMap:
          name: example-configmap
      containers:
      - name: nginx
        image: nginx
        ports:
      volumeMounts:
        - name: example-configmap-volume
